version: '3.8'

services:
  candy_app:
    image: candy_app_api
    build:
      context: .
      dockerfile: ./docker/node18/Dockerfile
    restart: unless-stopped
    command: npm run start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '${APP_PORT:-3000}:3000'
    environment:
      NODE_ENV: ${NODE_ENV}
    networks:
      - candy
    depends_on:
      - mysql

  mysql:
    image: 'mysql:8'
    platform: linux/x86_64
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'candymysql:/var/lib/mysql'
      - ./docker/node18/create-db.sh:/docker-entrypoint-initdb.d/create-db.sh
    networks:
      - candy
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]


networks:
  candy:
    driver: bridge

volumes:
  candymysql:
    driver: local